# choreo/component-config.yaml

name: jmusicbot
component:
  type: container
  source:
    image: musicbot:latest
    # If your image is hosted in a public registry, specify the registry URL
    # image: your-registry-url/musicbot:latest
  env:
    # Add any environment variables required by JMusicBot here
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx1024m"
  ports:
    - name: http
      protocol: TCP
      port: 2333
  volumeMounts:
    # Mount any volumes if required
    - name: config-volume
      mountPath: /app/config

volumes:
  - name: config-volume
    configMap:
      name: jmusicbot-config

configMaps:
  - name: jmusicbot-config
    data:
      config.txt: |
        # Your config.txt content goes here
      serversettings.json: |
        # Your serversettings.json content goes here

networking:
  ingress:
    enabled: false
    rules:
      - host: jmusicbot.example.com
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: jmusicbot
                  port:
                    number: 2333
